# .github/workflows/terraform.yml

name: Terraform

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Log in to Azure
    #- name: Azure Login
    #  uses: azure/login@v2
    #  with:
    #    auth-type: SERVICE_PRINCIPAL
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install the latest version of Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize the Terraform project
    - name: Terraform Init
      #run: terraform init -backend-config="storage_account_name=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=terraform-state" -backend-config="key=remanufacturing.tfstate" -backend-config="access_key=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_KEY }}"
      run: terraform init -backend-config="storage_account_name=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=terraform-state" -backend-config="key=remanufacturing.tfstate"
      working-directory: ./infra

    # Generate and show an execution plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./infra

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./infra